using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace mango.product.repository.Entities.Base
{
    /// <summary>
    /// Base entity for all the entities
    /// </summary>
    public class BaseEntity<K>
    {
        /// <summary>
        /// Primary Key AutoGenerated Key
        /// </summary>
        [Column(name: "Id")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key]
        public K Id { get; set; }
    }
}
